# Generated by Django 3.0.8 on 2020-09-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredients',
            field=models.TextField(default='some'),
        ),
    ]
