# Generated by Django 3.0.8 on 2020-09-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
