# Generated by Django 3.0.8 on 2020-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_auto_20200926_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(default='', upload_to='foto_receta'),
            preserve_default=False,
        ),
    ]
