# Generated by Django 3.0.8 on 2020-09-25 12:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recetas', '0004_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='likes',
            field=models.ManyToManyField(related_name='receta_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
