# Generated by Django 3.0.8 on 2020-09-26 13:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20200925_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredients',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Receta'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recetas.Receta')),
            ],
        ),
    ]
