# Generated by Django 3.1 on 2020-10-13 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_receta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informer', models.CharField(max_length=200)),
                ('informed', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, null=True)),
                ('options', models.PositiveSmallIntegerField(choices=[(1, 'Receta inválida'), (2, 'Spam'), (3, 'Otro')])),
                ('text', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_report', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[(0, 'Entradas'), (1, 'Carnes'), (2, 'Pastas'), (3, 'Veggie'), (4, 'Sandwiches'), (5, 'Sopas'), (6, 'Postres')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
