# Generated by Django 3.1 on 2020-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_auto_20201013_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Entradas'), (1, 'Carnes'), (2, 'Pastas'), (3, 'Veggie'), (4, 'Sandwiches'), (5, 'Sopas'), (6, 'Postres')]),
        ),
    ]
